// Deterministic structurally-valid fuzz fixture generator.
//
// Builds every committed fixture under test/resources/fuzz/generated/
// from fixed seeds. Hermetic: no network, no clock, no randomness
// beyond the seeds. `--check` regenerates in memory and byte-compares
// with the committed files (CI-safe drift gate).
//
//     dart run tool/generate_fuzz_fixtures.dart            # (re)write
//     dart run tool/generate_fuzz_fixtures.dart --check    # verify only
//     dart run tool/generate_fuzz_fixtures.dart --out=DIR  # alternate dir
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'fuzz/cfi_strings.dart';
import 'fuzz/epub_generator.dart';
import 'fuzz/image_bits.dart';
import 'fuzz/pdb_builder.dart';
import 'fuzz/pdf_builder.dart';
import 'fuzz/seeded_random.dart';
import 'fuzz/xml_documents.dart';
import 'fuzz/zip_builder.dart';

/// Where the committed fixtures live (relative to the repository root).
const String defaultOutputRoot = 'test/resources/fuzz/generated';

Future<void> main(final List<String> arguments) async {
  final checkOnly = arguments.contains('--check');
  final outRoot = _value(arguments, '--out=') ?? defaultOutputRoot;
  final plan = buildCorpusPlan();

  var mismatches = 0;
  var written = 0;
  for (final fixture in plan) {
    final path = '$outRoot/${fixture.relativePath}';
    if (checkOnly) {
      final existing = File(path);
      if (!existing.existsSync()) {
        stderr.writeln('MISSING  ${fixture.relativePath}');
        mismatches++;
        continue;
      }
      if (!bytesEqual(existing.readAsBytesSync(), fixture.bytes)) {
        stderr.writeln('DRIFT    ${fixture.relativePath} (regenerated bytes differ)');
        mismatches++;
      }
      continue;
    }
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsBytesSync(fixture.bytes, flush: true);
    written++;
  }

  if (checkOnly) {
    if (mismatches > 0) {
      stderr.writeln(
        'fixture check FAILED: $mismatches drifted or missing file(s); '
        'run dart run tool/generate_fuzz_fixtures.dart to refresh.',
      );
      exitCode = 65;
      return;
    }
    stdout.writeln('fixture check OK: ${plan.length} fixtures reproduce byte-identically.');
    return;
  }
  stdout.writeln(
    'fixture generation wrote $written files under $outRoot (plan size ${plan.length}).',
  );
}

/// One planned output file.
final class GeneratedFixture {
  const GeneratedFixture(this.relativePath, this.bytes, this.note);

  /// Path relative to the generation root.
  final String relativePath;

  /// Deterministic bytes.
  final Uint8List bytes;

  /// What the fixture exercises (documented in PROVENANCE.md).
  final String note;
}

/// The full deterministic fixture plan: every committed fuzz fixture.
///
/// Seeds are FIXED here on purpose — changing a seed changes committed
/// bytes and requires a regeneration commit.
List<GeneratedFixture> buildCorpusPlan() {
  final cover = tinyPng(0x30);
  final epub2 = buildEpub(syntheticEpubSpec(1, epub3: false));
  final epub3Nav = buildEpub(syntheticEpubSpec(2, epub3: true, withNav: true, withNcx: false));
  final epub3Cover = buildEpub(syntheticEpubSpec(3, epub3: true, withNav: true, coverPng: cover));
  final epubNoNcxNoNav = buildEpub(syntheticEpubSpec(4, withNcx: false));
  final storedZip = buildZip([
    ZipEntrySpec('stored-a.txt', utf8.encode('stored entry alpha'), method: ZipMethod.stored),
    ZipEntrySpec('stored-b.txt', utf8.encode('stored entry beta'), method: ZipMethod.stored),
  ], archiveComment: 'fuzz corpus stored-method archive');
  final mixedZip = buildZip([
    ZipEntrySpec('deflate/one.txt', utf8.encode('deflate ' * 40)),
    ZipEntrySpec(
      'deflate/two.txt',
      utf8.encode('second entry with a comment'),
      comment: 'entry comment',
    ),
    ZipEntrySpec(
      'deflate/nested/three.bin',
      Uint8List.fromList(List<int>.generate(256, (final i) => i)),
    ),
  ]);

  final random1 = SeededRandom(11);
  final random2 = SeededRandom(12);
  final random3 = SeededRandom(13);
  final random4 = SeededRandom(14);
  final fb2Xml = buildXmlDocument(fb2StyleSpec(random1));
  final opfXml = buildXmlDocument(opfStyleSpec(random2));
  final dtdXml = buildXmlDocument(doctypeInternalSubsetSpec(random3));
  final prologueXml = buildXmlDocument(prologueVariationSpec(random4));
  final bomXml = buildXmlDocument(
    XmlDocumentSpec(root: 'package', body: opfStyleSpec(SeededRandom(15)).body, withBom: true),
  );

  return [
    GeneratedFixture('epub/epub2-basic.epub', epub2, 'EPUB 2 OPF + NCX, 1-4 chapters'),
    GeneratedFixture('epub/epub3-nav.epub', epub3Nav, 'EPUB 3 with nav document, no NCX'),
    GeneratedFixture('epub/epub3-cover.epub', epub3Cover, 'EPUB 3 nav + PNG cover-image'),
    GeneratedFixture('epub/epub-no-toc.epub', epubNoNcxNoNav, 'EPUB without NCX and without nav'),
    GeneratedFixture(
      'zip/stored-method.zip',
      storedZip,
      'ZIP with method-0 entries and archive comment',
    ),
    GeneratedFixture(
      'zip/mixed-methods.zip',
      mixedZip,
      'ZIP mixing deflate/stored, comments, nested dirs',
    ),
    GeneratedFixture(
      'xml/fb2-style.fb2',
      fb2Xml,
      'FB2-shaped XML: namespaces, entities, CDATA, comment',
    ),
    GeneratedFixture('xml/opf-style.opf', opfXml, 'OPF-shaped XML with refines/metadata'),
    GeneratedFixture('xml/dtd-internal-subset.xml', dtdXml, 'XML with internal DTD entity subset'),
    GeneratedFixture(
      'xml/prologue-variations.xml',
      prologueXml,
      'PI + leading comment, no XML declaration',
    ),
    GeneratedFixture('xml/utf8-bom.opf', bomXml, 'OPF XML with UTF-8 BOM'),
    GeneratedFixture(
      'cfi/cfi-cases.json',
      buildCfiCaseJson(42),
      'Valid + malformed EPUB CFI strings',
    ),
    GeneratedFixture(
      'pdf/minimal-text.pdf',
      minimalTextPdf(),
      'Single page, uncompressed content stream',
    ),
    GeneratedFixture(
      'pdf/flate-content.pdf',
      minimalTextPdf(filter: PdfStreamFilter.flate),
      'Content stream /FlateDecode',
    ),
    GeneratedFixture(
      'pdf/lzw-content.pdf',
      minimalTextPdf(filter: PdfStreamFilter.lzw),
      'Content stream /LZWDecode EarlyChange=1',
    ),
    GeneratedFixture(
      'pdf/two-page-flate.pdf',
      twoPagePdf(PdfStreamFilter.flate),
      'Two pages with Flate content',
    ),
    GeneratedFixture(
      'pdf/info-metadata.pdf',
      pdfWithInfo(),
      'Info dictionary with synthetic Title/Author',
    ),
    GeneratedFixture(
      'mobi/palmdoc-none.mobi',
      syntheticMobi(21),
      'MOBI compression=1 (none), EXTH 100/503',
    ),
    GeneratedFixture(
      'mobi/palmdoc-compressed.mobi',
      syntheticMobi(22, palmDocCompression: true),
      'MOBI compression=2 PalmDOC LZ77',
    ),
    GeneratedFixture('images/tiny-gray.png', tinyPng(0x80), '1x1 grayscale PNG'),
    GeneratedFixture(
      'images/gradient.png',
      buildPng(8, 8, (final x, final y) => (x * 30 + y * 2) & 0xFF),
      '8x8 gradient PNG',
    ),
    GeneratedFixture('images/tiny.jpg', tinyJpeg(), 'Minimal baseline grayscale JPEG'),
    GeneratedFixture('images/tiny.gif', tinyGif(), 'Minimal GIF89a, 2-color GCT'),
    GeneratedFixture('images/gif87a.gif', tinyGif(variant: 1), 'Minimal GIF87a variant'),
    GeneratedFixture(
      'images/png-bad-crc.png',
      pngWithBadCrc(),
      'PNG with corrupted IDAT CRC (lenient parse)',
    ),
    GeneratedFixture(
      'images/png-truncated-idat.png',
      pngTruncatedIdat(),
      'PNG cut inside IDAT, no IEND',
    ),
    GeneratedFixture(
      'images/jpeg-truncated-scan.jpg',
      jpegTruncatedScan(),
      'JPEG cut inside scan data, no EOI',
    ),
  ];
}

/// Byte equality for fixture comparison.
bool bytesEqual(final Uint8List a, final Uint8List b) {
  if (a.length != b.length) {
    return false;
  }
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) {
      return false;
    }
  }
  return true;
}

String? _value(final List<String> arguments, final String prefix) {
  for (final argument in arguments) {
    if (argument.startsWith(prefix)) {
      return argument.substring(prefix.length);
    }
  }
  return null;
}
