import 'dart:io';

import 'package:test/test.dart';
import 'package:unseal/unseal.dart';

/// The parser against a real corpus: eight Project Gutenberg books rendered
/// by a genuine PDF writer (macOS cupsfilter), fetched and regenerated by
/// `tool/fetch_pdf_corpus.dart` — see `test/resources/pdf/gutenberg/MANIFEST.md`.
void main() {
  final corpusDir = Directory('test/resources/pdf/gutenberg');
  if (!corpusDir.existsSync()) {
    fail('missing $corpusDir; run `dart run tool/fetch_pdf_corpus.dart`');
  }
  final fixtures =
      corpusDir
          .listSync()
          .whereType<File>()
          .where((final file) => file.path.endsWith('.pdf'))
          .toList()
        ..sort((final a, final b) => a.path.compareTo(b.path));
  if (fixtures.isEmpty) {
    fail('empty $corpusDir; run `dart run tool/fetch_pdf_corpus.dart`');
  }

  final books = <File, PdfBook>{};

  setUpAll(() {
    for (final fixture in fixtures) {
      books[fixture] = parsePdfBook(fixture.readAsBytesSync());
    }
  });

  group('Gutenberg corpus book', () {
    for (final fixture in fixtures) {
      final name = fixture.uri.pathSegments.last;

      test('$name parses with pages, format and metadata', () {
        final book = books[fixture]!;

        expect(book.pageCount, greaterThan(0));
        expect(book.format, BookFormat.pdf);
        expect(book.metadata, isNotNull);
        // One reflowed page document per document page.
        expect(book.files.html, hasLength(book.pageCount));
      });

      test('$name carries a text layer', () {
        // Every corpus book comes from a text render, never a scan.
        expect(books[fixture]!.hasTextLayer, isTrue, reason: '$name should expose a text layer');
      });

      test('$name keeps the canonical invariant on the first pages', () {
        final book = books[fixture]!;
        final checked = book.pageCount < 10 ? book.pageCount : 10;

        for (var i = 0; i < checked; i++) {
          expect(
            DocumentTextScanner(book.files.html[i].content).scan(),
            book.pageTexts[i].text,
            reason: 'page $i of $name breaks the canonical invariant',
          );
        }
      });

      test('$name finds a common word', () {
        expect(books[fixture]!.search('the').matches, isNotEmpty);
      });
    }
  });

  test('Unseal.read parses a corpus book in the isolate', () async {
    final bytes = fixtures.first.readAsBytesSync();

    final book = await Unseal.read(bytes);

    expect(book, isA<PdfBook>());
    final pdf = book as PdfBook;
    expect(pdf.pageCount, greaterThan(0));
    // The invariant survives the isolate round trip on the first page.
    expect(DocumentTextScanner(pdf.files.html.first.content).scan(), pdf.pageTexts.first.text);
  });
}
